export const SCALEV_TOOL_NAMES = [
  "get_me",
  "get_docs",
  "search",
  "get",
  "execute_safe",
  "execute_destructive",
  "list_landing_pages",
  "list_landing_page_tags",
  "get_landing_page",
  "get_landing_page_public_view",
  "create_landing_page",
  "update_landing_page",
  "update_landing_page_tags",
  "delete_landing_page",
  "list_landing_page_displays",
  "create_landing_page_display",
  "validate_landing_page_display",
  "get_landing_page_display",
  "delete_landing_page_display",
  "list_orders",
  "get_order",
  "create_order",
  "update_order",
  "change_order_status",
  "get_order_statistics"
] as const;
